[build]
  command = "npm run build"
  publish = "dist/pages"

# Set CORS headers for all resources (required for embedding in Shopify)
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

# Cache static assets for 1 year
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache embed HTML files for 1 hour (allows faster updates)
[[headers]]
  for = "/pages/*.embed.html"
  [headers.values]
    Cache-Control = "public, max-age=3600, s-maxage=3600"

# Cache regular HTML for 1 hour
[[headers]]
  for = "/pages/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600, s-maxage=3600"

